<a href="https://colab.research.google.com/github/happodaikarin/PythonFiles/blob/main/TALLER2_SIMULACION_COMPUTACIONAL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

IMPORTAMOS LIBRERIAS



In [ ]:
import numpy as np
import random
from scipy.stats import kstest, chisquare, chi2, norm

PUNTO1
- GENERADOR LINEAL CONGURENTE
-
- GENERADOR ESTANDAR MINIMO

In [ ]:
def linear_congruential_generator(a, c, m, X0, n):
    values = []
    Xn = X0
    for _ in range(n):
        X_next = (a * Xn + c) % m
        values.append(X_next / float(m))
        Xn = X_next
    return values

# Parámetros
a, c, m, X0 = 8,13,97, 8
n = 500  # Número de valores a generar
lcg_values = linear_congruential_generator(a, c, m, X0, n)
print(lcg_values)


[0.7938144329896907, 0.4845360824742268, 0.010309278350515464, 0.21649484536082475, 0.865979381443299, 0.061855670103092786, 0.6288659793814433, 0.16494845360824742, 0.4536082474226804, 0.7628865979381443, 0.23711340206185566, 0.030927835051546393, 0.38144329896907214, 0.18556701030927836, 0.6185567010309279, 0.08247422680412371, 0.7938144329896907, 0.4845360824742268, 0.010309278350515464, 0.21649484536082475, 0.865979381443299, 0.061855670103092786, 0.6288659793814433, 0.16494845360824742, 0.4536082474226804, 0.7628865979381443, 0.23711340206185566, 0.030927835051546393, 0.38144329896907214, 0.18556701030927836, 0.6185567010309279, 0.08247422680412371, 0.7938144329896907, 0.4845360824742268, 0.010309278350515464, 0.21649484536082475, 0.865979381443299, 0.061855670103092786, 0.6288659793814433, 0.16494845360824742, 0.4536082474226804, 0.7628865979381443, 0.23711340206185566, 0.030927835051546393, 0.38144329896907214, 0.18556701030927836, 0.6185567010309279, 0.08247422680412371, 0.7938

In [ ]:
def min_std_generator(a, m, X0, n):
    values = []
    Xn = X0
    q = m // a
    r = m % a
    for _ in range(n):
        Xn = ((a * (Xn % q)) - (r * (Xn // q)))
        if Xn < 0:
            Xn = Xn + m
        values.append(Xn / m)
    return values

a, m, X0 = 7**5, 2**31 - 1, 32423
n = 500
min_std_values = min_std_generator(a, m, X0, n)
print(min_std_values)


[0.2537543704983566, 0.849704965879072, 0.991361529562325, 0.8132273539962375, 0.912138614762639, 0.31369831567336726, 0.3275915222836619, 0.8307150215053535, 0.8273664404765546, 0.5477650894540199, 0.28785845371329155, 0.03703155929084474, 0.3894170012275768, 0.931539631882468, 0.386593048640803, 0.46936850597586877, 0.676479936426729, 0.598291524033198, 0.4856444259572981, 0.22586706430924455, 0.14774984547297929, 0.23165286436288285, 0.3896913469721057, 0.542468560180845, 0.2690909594619139, 0.6117556763867641, 0.7776530323446044, 0.014514615766012397, 0.9471471793703489, 0.7026436774538102, 0.33228696618801307, 0.7470407219357047, 0.5134135733886686, 0.941927943351645, 0.982943911097452, 0.3383138148758159, 0.040286617837979745, 0.09718600292559061, 0.40515117040143867, 0.37572093697996856, 0.7417878223312031, 0.22792992052991407, 0.8181743462654643, 0.05623768365766745, 0.18674923441687097, 0.694382844350479, 0.4924649985006382, 0.8592298002258082, 0.07525239515828545, 0.767005425

PUNTO 2
- GENERAR PRUEBAS UNIFORMINDAD
- X²
- KOLMOROV

In [ ]:
def chi_square_test(data, num_intervals):
    observed_frequencies, _ = np.histogram(data, bins=num_intervals)
    expected_frequencies = np.ones_like(observed_frequencies) * (len(data) / num_intervals)
    chi_square_stat = chisquare(observed_frequencies, f_exp=expected_frequencies).statistic
    return chi_square_stat

num_intervals = 10
alpha = 0.05  # Nivel de significancia

chi_stat_lcg = chi_square_test(lcg_values, num_intervals)
chi_stat_minstd = chi_square_test(min_std_values, num_intervals)
df = num_intervals - 1  # Grados de libertad
chi_critical_value = chi2.ppf(1 - alpha, df)
def interpretar_chi_cuadrado(chi_stat, chi_critical_value):
    return "Aceptar H0: Distribución uniforme" if chi_stat <= chi_critical_value else "Rechazar H0: No es una distribución uniforme"

print("Resultados de la prueba Chi-cuadrado:")
print(f"{'Generador':<30}{'Chi-cuadrado Estadístico':<30}{'Valor Crítico de Chi-cuadrado':<30}{'Interpretación':<30}")
print(f"{'LCG':<30}{chi_stat_lcg:<30.2f}{chi_critical_value:<30.2f}{interpretar_chi_cuadrado(chi_stat_lcg, chi_critical_value):<30}")
print(f"{'Min Std':<30}{chi_stat_minstd:<30.2f}{chi_critical_value:<30.2f}{interpretar_chi_cuadrado(chi_stat_minstd, chi_critical_value):<30}")



Resultados de la prueba Chi-cuadrado:
Generador                     Chi-cuadrado Estadístico      Valor Crítico de Chi-cuadrado Interpretación                
LCG                           282.52                        16.92                         Rechazar H0: No es una distribución uniforme
Min Std                       5.72                          16.92                         Aceptar H0: Distribución uniforme


In [ ]:
def kolmogorov_smirnov_test(data, alpha=0.05):
    n = len(data)
    statistic, p_value = kstest(data, 'uniform')
    K_alpha = 1.36  # Valor para un nivel de significancia de 0.05
    critical_value = K_alpha / np.sqrt(n)
    return statistic, critical_value


ks_stat_lcg, ks_critical_lcg = kolmogorov_smirnov_test(lcg_values)
ks_stat_minstd, ks_critical_minstd = kolmogorov_smirnov_test(min_std_values)

def interpretar_ks(statistic, critical_value):
    return "Aceptar H0: Distribución uniforme" if statistic <= critical_value else "Rechazar H0: No es una distribución uniforme"

print("Resultados de la prueba Kolmogorov-Smirnov:")
print(f"{'Generador':<30}{'K-S Estadístico':<30}{'Valor Crítico de K-S':<30}{'Interpretación':<30}")
print(f"{'LCG':<30}{ks_stat_lcg:<30.4f}{ks_critical_lcg:<30.4f}{interpretar_ks(ks_stat_lcg, ks_critical_lcg):<30}")
print(f"{'Min Std':<30}{ks_stat_minstd:<30.4f}{ks_critical_minstd:<30.4f}{interpretar_ks(ks_stat_minstd, ks_critical_minstd):<30}")


Resultados de la prueba Kolmogorov-Smirnov:
Generador                     K-S Estadístico               Valor Crítico de K-S          Interpretación                
LCG                           0.0493                        0.0608                        Aceptar H0: Distribución uniforme
Min Std                       0.0265                        0.0608                        Aceptar H0: Distribución uniforme


PUNTO 3
- PRUEBA DE CORRIDAS
- PRUEBA DE SERIE
- PRUEBA DE POKER

In [ ]:
import numpy as np

def runs_test(values, alpha=0.05):
    runs = 0
    n1 = 0
    n2 = 0
    runs_serie = ""

    # Calcular + y -
    for i in range(1, len(values)):
        if values[i] > values[i-1]:
            n1 += 1
            runs_serie += "+"
        else:
            n2 += 1
            runs_serie += "-"

    # Calcular corridas (+ o -)
    prev_run = runs_serie[0]
    for i in range(1, len(runs_serie)):
        if runs_serie[i] != prev_run:
            runs += 1
            prev_run = runs_serie[i]
    runs += 1  # La última corrida

    # Calcular estadísticas
    mu = (2*n1*n2) / (n1 + n2) + 1
    sigma_sq = (2*n1*n2*(2*n1*n2 - n1 - n2)) / ((n1 + n2)**2 * (n1 + n2 - 1))
    z = (runs - mu) / np.sqrt(sigma_sq)

    # Valor crítico para la prueba bilateral
    z_critical = norm.ppf(1 - alpha/2)

    print(f"Secuencia de + y -: {runs_serie}")
    print(f"Número total de corridas: {runs}")

    return {
        'n1': n1,
        'n2': n2,
        'runs': runs,
        'mu': mu,
        'sigma_sq': sigma_sq,
        'z': z,
        'z_critical': z_critical,
        'result': abs(z) < z_critical
    }


result_min_std_values = runs_test(min_std_values)
results_lcg = runs_test(lcg_values)

print("Prueba de corridas para LCG:", results_lcg)

print("Prueba de corridas para STD - MIN:", result_min_std_values)

Secuencia de + y -: ++-+-++----++-++----+++-++-+--+-++--++-+-+-++-+-+-+--++-+-+--+-+--+--+-+-+--+---+-+-+--+-+-+---+--+-+++-+-+--++-++----+-+-+-+-+-++------+---++-+--+--++-+-+-+--+-++-+-+-+--++-++--+++-+-+-+--+--+---++-+--+--+-+-++-+-+++--+--+--+-+-+-+-+-+++--++-+-+-++-+--++-+-++-+-++++-++--+-++-+--+--++--++--+-+-+-++-++-++-+--+---+-+-+-+-++---++-++--+--+-+-+-+-+-++---++--+-++-+--+-+-+-+++-+-+-+---+--+--+++--+-+-+-++----++-++-+-+-+-++-++-+-+-++-++-+-+-+-+-++-+-+++---++++--+-+-++-+-+-++--+-+--+-+++-+--+-+-+-++-+-++
Número total de corridas: 351
Secuencia de + y -: -+--+-+-+--++-+-+-+++-+-++--+-++-+-+--++-+-++--+++--++-+-+--+-+++-+-+-+-++-+--+-+-+---+--+-+-+-++--+--+---+-++-+-+-+--+-++-+-++-++--+-+--+-+++-+-+-+--+--+-++--+-+-++-+--+++----+-+++-++-++-++-+++-++--+--+-++--++--+-++--+-+-+-++--+-+-+-+---+--+++---+-++-+-+--+--+-++--+-+---+++---+-+--++--++-+--+--+-+--+-+-+-+-++-+-+-+-----++-+++--++++-+-+-+-+--+++-+-++-+--+-++-+-++-+-+--+-+--++--+-+--+--++-++-++-+-+--+-+-+---++-+-++-+-+++---+-+-

In [ ]:
import numpy as np
from scipy.stats import chisquare, chi2


# Función para el test de series
def series_test(data, k):
    n = len(data) - 1
    fe = (n / (k ** 2))

    observed_matrix = np.zeros((k, k))
    intervals = np.linspace(0, 1, k + 1)

    for i in range(n):
        for j in range(k):
            if intervals[j] <= data[i] < intervals[j+1]:
                for m in range(k):
                    if intervals[m] <= data[i+1] < intervals[m+1]:
                        observed_matrix[j][m] += 1

    observed = observed_matrix.flatten()
    expected = np.full(k**2, fe)
    if not np.isclose(observed.sum(), expected.sum(), rtol=1e-5):
        print("La suma de las frecuencias observadas no coincide con la esperada.")
        difference = expected.sum() - observed.sum()
        expected += difference / (k**2)

    chi_stat, p_value = chisquare(observed, f_exp=expected)

    return observed_matrix, chi_stat, p_value


from scipy.stats import chisquare, chi2

k = 5  # Número de intervalos
# Realiza la prueba de series
observed_matrix_lcg, chi_stat_lcg, p_value_lcg = series_test(lcg_values, k)
observed_matrix_minstd, chi_stat_minstd, p_value_minstd = series_test(min_std_values, k)

# Grados de libertad para la prueba de chi-cuadrado
degrees_of_freedom = k**2 - 1

# Valor crítico de chi-cuadrado al nivel de significancia deseado
alpha = 0.05
chi_crit = chi2.ppf(1 - alpha, degrees_of_freedom)

# Imprime los resultados
print("LCG - Matriz de Observados:")
print(observed_matrix_lcg)
print("LCG - Estadístico de Chi-Cuadrado:", chi_stat_lcg)
print("LCG - Valor crítico de Chi-Cuadrado:", chi_crit)

print("\nMinStd - Matriz de Observados:")
print(observed_matrix_minstd)
print("MinStd - Estadístico de Chi-Cuadrado:", chi_stat_minstd)
print("MinStd - Valor crítico de Chi-Cuadrado:", chi_crit)

# Decisión basada en el valor crítico
if chi_stat_lcg > chi_crit:
    print("\nLCG: Rechazar la hipótesizar de independecia.")
else:
    print("\nLCG: Acepta la hipotesis de independencia.")

if chi_stat_minstd > chi_crit:
    print("MinStd: Rechazar la hipótes de independecia")
else:
    print("MinStd: Acepta la hipotesis de independencia.")


LCG - Matriz de Observados:
[[ 0. 63. 31. 93.  0.]
 [62.  0.  0.  0. 31.]
 [32.  0.  0. 31.  0.]
 [62. 31. 32.  0.  0.]
 [31.  0.  0.  0.  0.]]
LCG - Estadístico de Chi-Cuadrado: 861.6713426853706
LCG - Valor crítico de Chi-Cuadrado: 36.41502850180731

MinStd - Matriz de Observados:
[[14. 17. 21. 17. 23.]
 [16. 29. 16. 32. 21.]
 [20. 19. 15. 21. 18.]
 [27. 23. 24. 14. 15.]
 [15. 25. 17. 19. 21.]]
MinStd - Estadístico de Chi-Cuadrado: 27.50300601202405
MinStd - Valor crítico de Chi-Cuadrado: 36.41502850180731

LCG: Rechazar la hipótesizar de independecia.
MinStd: Acepta la hipotesis de independencia.


PARA 3

In [ ]:
from scipy.stats import chi2

def categorize_in_threes(values):
    patterns = {'todos_diferentes': 0, 'un_par': 0, 'tres_iguales': 0}
    for i in range(0, len(values), 3):
        hand = sorted(values[i:i+3])
        if len(hand) < 3: continue
        counts = list(map(hand.count, hand))
        pattern = (len(set(counts)), max(counts))
        if pattern == (3, 1):
            patterns['todos_diferentes'] += 1
        elif pattern == (1, 3):
            patterns['tres_iguales'] += 1
        elif pattern == (2, 2):
            patterns['un_par'] += 1
    return patterns

# Función para realizar la prueba chi-cuadrado
def perform_chi_squared_test(values, n):
    patterns = categorize_in_threes(values)
    observed = list(patterns.values())
    probabilities = {'todos_diferentes': 0.720, 'un_par': 0.270, 'tres_iguales': 0.010}
    expected = [n * probabilities[pattern] for pattern in patterns]
    chi_squared = sum((o - e) ** 2 / e for o, e in zip(observed, expected))
    df = len(patterns) - 1
    critical_value = chi2.ppf(1 - alpha, df)
    return chi_squared, critical_value

n_groups = n // 3

# Prueba para LCG
chi_squared_lcg, critical_value_lcg = perform_chi_squared_test(lcg_values, n_groups)
print("LCG Chi cuadrado:", chi_squared_lcg)
print("LCG Valor crítico:", critical_value_lcg)
print("Hipótesis nula LCG", "rechazada" if chi_squared_lcg > critical_value_lcg else "aceptada")

# Prueba para MinStd
chi_squared_minstd, critical_value_minstd = perform_chi_squared_test(min_std_values, n_groups)
print("MinStd Chi cuadrado:", chi_squared_minstd)
print("MinStd Valor crítico:", critical_value_minstd)
print("Hipótesis nula MinStd", "rechazada" if chi_squared_minstd > critical_value_minstd else "aceptada")



LCG Chi cuadrado: 166.0
LCG Valor crítico: 5.991464547107979
Hipótesis nula LCG rechazada
MinStd Chi cuadrado: 166.0
MinStd Valor crítico: 5.991464547107979
Hipótesis nula MinStd rechazada


PARA 5

In [ ]:
from scipy.stats import chi2

# Probabilidades esperadas para cada patrón
probabilities = {
    'todos_diferentes': 0.3024,
    'un_par': 0.5040,
    'dos_pares': 0.1080,
    'tercia': 0.0720,
    'full': 0.0090,
    'poker': 0.0045,
    'quintilla': 0.0001
}

# Función para calcular la prueba de chi-cuadrado
def calculate_chi_squared(observed_counts, expected_probabilities, total_samples):
    expected_counts = [total_samples * p for p in expected_probabilities]
    chi_squared_stat = sum((o - e) ** 2 / e for o, e in zip(observed_counts, expected_counts))
    return chi_squared_stat

# Función para realizar la prueba de chi cuadrado para una secuencia de números
def poker_test(values):
    patterns = {'todos_diferentes': 0, 'un_par': 0, 'dos_pares': 0, 'tercia': 0,
                'full': 0, 'poker': 0, 'quintilla': 0}
    for i in range(0, len(values), 5):
        hand = sorted(values[i:i+5])
        if len(hand) < 5:
            continue
        counts = list(map(hand.count, hand))
        pattern = (len(set(counts)), max(counts))
    chi_squared_stat = calculate_chi_squared(list(patterns.values()), list(probabilities.values()), len(values) // 5)
    alpha = 0.05
    degrees_of_freedom = len(patterns) - 1
    critical_value = chi2.ppf(1 - alpha, degrees_of_freedom)
    if chi_squared_stat > critical_value:
        decision = 'rechazada'
    else:
        decision = 'aceptada'
    return chi_squared_stat, critical_value, decision

# Realiza la prueba para LCG
chi_squared_lcg, critical_value_lcg, decision_lcg = poker_test(lcg_values)
print("LCG Chi cuadrado:", chi_squared_lcg)
print("LCG Valor crítico:", critical_value_lcg)
print(f"Hipótesis nula LCG {decision_lcg}")

# Realiza la prueba para MinStd
chi_squared_minstd, critical_value_minstd, decision_minstd = poker_test(min_std_values)
print("MinStd Chi cuadrado:", chi_squared_minstd)
print("MinStd Valor crítico:", critical_value_minstd)
print(f"Hipótesis nula MinStd {decision_minstd}")

LCG Chi cuadrado: 100.00000000000001
LCG Valor crítico: 12.591587243743977
Hipótesis nula LCG rechazada
MinStd Chi cuadrado: 100.00000000000001
MinStd Valor crítico: 12.591587243743977
Hipótesis nula MinStd rechazada


PUNTO4

In [ ]:
import numpy as np
from scipy.stats import chi2, chisquare
import random

random_values = [random.random() for _ in range(n)]
chi_stat_random = chi_square_test(random_values, num_intervals)

interpretacion = interpretar_chi_cuadrado(chi_stat_random, chi_critical_value)
print("Resultados de la prueba Chi-cuadrado para números generados por random.random():")
print(f"Chi-cuadrado Estadístico: {chi_stat_random:.2f}")
print(f"Valor Crítico de Chi-cuadrado: {chi_critical_value:.2f}")
print(f"Interpretación: {interpretacion}")


Resultados de la prueba Chi-cuadrado para números generados por random.random():
Chi-cuadrado Estadístico: 3.56
Valor Crítico de Chi-cuadrado: 16.92
Interpretación: Aceptar H0: Distribución uniforme


In [ ]:
ks_statistic, ks_p_value = kstest(random_values, 'uniform')
K_alpha = 1.36 / np.sqrt(n)
print("Resultados de la prueba Kolmogorov-Smirnov para números generados por random.random():")
print(f"K-S Estadístico: {ks_statistic:.4f}")
print(f"Valor Crítico de K-S: {K_alpha:.4f}")
print(f"p-value: {ks_p_value:.4f}")
interpretation = "Aceptar H0: Distribución uniforme" if ks_statistic <= K_alpha else "Rechazar H0: No es una distribución uniforme"
print(f"Interpretación: {interpretation}")

Resultados de la prueba Kolmogorov-Smirnov para números generados por random.random():
K-S Estadístico: 0.0326
Valor Crítico de K-S: 0.0608
p-value: 0.6487
Interpretación: Aceptar H0: Distribución uniforme


In [ ]:
# Aplicar la prueba de corridas a los números aleatorios generados
results_random = runs_test(random_values)

# Imprimir los resultados de la prueba de corridas
print("Prueba de corridas para números generados por random.random():")
print(f"Número de corridas: {results_random['runs']}")
print(f"Valor esperado (mu): {results_random['mu']:.2f}")
print(f"Varianza (sigma^2): {results_random['sigma_sq']:.2f}")
print(f"Estadístico Z: {results_random['z']:.2f}")
print(f"Valor crítico Z: ±{results_random['z_critical']:.2f}")
print(f"Resultado de la prueba: {'Aceptar' if results_random['result'] else 'Rechazar'} H0: la secuencia es aleatoria")


Secuencia de + y -: +-+-+++-++-+--++--+++-++-+--+--+--++---++-+-+-++-+-++-+-++-++---+-+--+++-+-+--++-++-+++--+++-+-++--++--++-++--+++-+--++-++--+++---+-++-+-++-+---+-+--++++-++-++--+-+--+-+-+--+-++-++--++-+-+--+-+-++-+--+-+-+-+-++---++-+-++-+-++--+-+-+-+-+--++-++-+--+++--+--+--+-+-++-+-+-+--+++-+++--+--++--+++-++--+-++-++-++--+-+--+--++--+++--++--++-+++---+--++-+-+++--++---+-+-+-+---+-++-+-+-++--+--++++--+-+-++-++-+--++-+-+-++--+++-+-+---+-+--+-+-+-++-+---++--++---+-++-+-++--++-+-+-++--+-+-+-+-+-++--+-+-+-+++-----
Número total de corridas: 330
Prueba de corridas para números generados por random.random():
Número de corridas: 330
Valor esperado (mu): 250.14
Varianza (sigma^2): 124.14
Estadístico Z: 7.17
Valor crítico Z: ±1.96
Resultado de la prueba: Rechazar H0: la secuencia es aleatoria


In [ ]:
observed_matrix_random, chi_stat_random, p_value_random = series_test(random_values, k)
degrees_of_freedom = k**2 - 1
alpha = 0.05
chi_crit = chi2.ppf(1 - alpha, degrees_of_freedom)
print("Random - Matriz de Observados:")
print(observed_matrix_random)
print("Random - Estadístico de Chi-Cuadrado:", chi_stat_random)
print("Random - Valor crítico de Chi-Cuadrado:", chi_crit)
if chi_stat_random > chi_crit:
    print("\nRandom: Rechazar la hipótesis de independencia.")
else:
    print("\nRandom: Aceptar la hipótesis de independencia.")

Random - Matriz de Observados:
[[11. 22. 20. 16. 17.]
 [16. 27. 21. 22. 19.]
 [24. 22. 21. 24. 25.]
 [16. 11. 23. 20. 21.]
 [20. 23. 30.  9. 19.]]
Random - Estadístico de Chi-Cuadrado: 29.106212424849698
Random - Valor crítico de Chi-Cuadrado: 36.41502850180731

Random: Aceptar la hipótesis de independencia.


In [ ]:
random_values = [random.random() for _ in range(n)]

n_groups = n // 3

# Realizar la prueba chi-cuadrado con los valores aleatorios generados
chi_squared_random, critical_value_random = perform_chi_squared_test(random_values, n_groups)

# Imprimir los resultados
print("Random Chi cuadrado:", chi_squared_random)
print("Random Valor crítico:", critical_value_random)
print("Hipótesis nula Random", "rechazada" if chi_squared_random > critical_value_random else "aceptada")

Random Chi cuadrado: 166.0
Random Valor crítico: 5.991464547107979
Hipótesis nula Random rechazada


poker 3

In [ ]:
n_groups = n // 3
chi_squared_random, critical_value_random = perform_chi_squared_test(random_values, n_groups)
# Imprime los resultados
print("Random Chi cuadrado:", chi_squared_random)
print("Random Valor crítico:", critical_value_random)
print("Hipótesis nula Random", "rechazada" if chi_squared_random > critical_value_random else "aceptada")

Random Chi cuadrado: 166.0
Random Valor crítico: 5.991464547107979
Hipótesis nula Random rechazada
